version: '3'
services:
  load_balancer_service:
    build: ./loadbalancer
    container_name: load_balancer
    ports:
      - "5000:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    # define a network called mynet
    networks:
      - mynet
networks:
  mynet:
    external: true