version: '3'
services:
  load_balancer_service:
    build: ./loadbalancer
    container_name: load_balancer
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # define a network called mynet
    networks:
      - mynet
networks:
  mynet:
    external: true