version: '3'
services:
  loadbalancer:
    # build: . 
    image: myloadbal
    ports:
      - "5000:5000"
    networks:
      - mynet
  server1:
    # build: ./server
    image: myserver
    ports:
      - "8081:8080"
    environment:
      - HOSTNAME=Server1
      - SERVER_IDENTIFIER=Server1
    networks:
      - mynet
  server2:
    # build: ./server
    image: myserver
    ports:
      - "8082:8080"
    environment:
      - HOSTNAME=Server2
      - SERVER_IDENTIFIER=Server2
    networks:
      - mynet
  server3:
    # build: ./server
    image: myserver
    ports:
      - "8083:8080"
    environment:
      - HOSTNAME=Server3
      - SERVER_IDENTIFIER=Server3
    networks:
      - mynet
networks:
  mynet: