version: '3'
services:
  spawner:
    # build: . 
    image: myspawner
    # ports:
    #   - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - mynet
  server1:
    # build: ./server
    image: myserver
    ports:
      - "8081:8080"
    environment:
      - HOSTNAME=Server1
      - SERVER_IDENTIFIER=Server1
    networks:
      - mynet
networks:
  mynet:
    name: mynet